### ISSUE TITLE
Expected behaviour inside 'let'

### ISSUE THREAD

**Issue by digikar99** [edicl/cl-who#30]
Is this supposed to work the way it is working currently:

```lisp
(let ((a "hello"))
  (with-html-output (var (make-string-output-stream))
    (htm (:a a))))
;=> "</a>"
;expected <a>hello</a>
```

If so, why and what is the work around?

**Comment by stassats** [comment]
Yes, expected, you need to use STR (or better, ESC for arbitrary strings).

**Comment by digikar99** [comment]
Something like this:

```lisp
(let ((a "hello"))
  (with-html-output (var (make-string-output-stream))
    (:a (str a))))
;=> "</a>" ; still; same with esc
```

**Comment by stassats** [comment]
well, it goes into your (make-string-output-stream), and then nowhere.

You need to either use with-html-output-to-string, use with-output-to-string, keep track of your own output-stream, or use some other stream.

**Comment by digikar99** [comment]
Hmm... Okay:

```lisp
(let ((a "hello"))
  (with-html-output-to-string (*standard-output*)
    (:a (str a))))
;=> "<a>hello</a>" ;; (:a a) yields "<a></a>" as the output
```

Thanks!
